name: Build and Deploy to Cloudflare R2

on:
  workflow_dispatch:

  push:
    branches:
      - main  # 自动触发的分支，您可以根据需要修改

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'  # 替换为您需要的 Go 版本

      - name: Install dependencies
        run: go mod tidy  # 如果使用 Go Modules

      - name: Build
        run: make

      - name: Upload to Cloudflare R2
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}  # 使用 GitHub Secrets
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}  # 使用 GitHub Secrets
          R2_BUCKET: ${{ secrets.R2_BUCKET }}  # 使用 GitHub Secrets
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}  # 使用 GitHub Secrets
        run: |
          # 配置 AWS CLI，以便与 R2 交互
          aws configure set aws_access_key_id $R2_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $R2_SECRET_ACCESS_KEY
          aws configure set default.region auto
          aws configure set default.s3.signature_version s3v4
          aws s3 sync ./bin s3://$R2_BUCKET/example_bin --region auto --endpoint-url https://$ACCOUNT_ID.r2.cloudflarestorage.com