name: Build and Deploy to S3

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main  # 自动触发的分支

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'  # 替换为您需要的 Go 版本

      - name: Install dependencies
        run: go mod tidy  # 如果使用 Go Modules

      - name: Run tests
        run: go test ./... -v  # 运行所有测试

      - name: Build
        run: make

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.0
        with:
          args: --acl public-read  # 根据需要调整权限
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: ./bin  # 指定要上传的目录
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
